import { neon } from '@neondatabase/serverless';import { admin } from './_auth.js';
function monthStart(v){const d=v?new Date(`${v}-01T12:00:00Z`):new Date();return new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1)).toISOString().slice(0,10);}
export default async function handler(req,res){if(req.method!=='POST'){res.status(405).json({ok:false,error:'Method not allowed.'});return;}if(!admin(req,res))return;try{const b=typeof req.body==='string'?JSON.parse(req.body):req.body||{},edition=monthStart(b.month),sql=neon(process.env.DATABASE_URL);const [needs,events,photos,resources,nonprofits,impact]=await Promise.all([
 sql`SELECT n.id,n.title,n.description,n.need_type,o.display_name,o.slug FROM organization_needs n JOIN organizations o ON o.id=n.organization_id WHERE n.status='approved' AND (n.ends_at IS NULL OR n.ends_at>=now()) AND o.active=true AND o.approval_status='approved' ORDER BY n.created_at DESC LIMIT 8`,
 sql`SELECT e.id,e.title,e.starts_at,e.location_name,e.event_url,o.display_name FROM organization_events e JOIN organizations o ON o.id=e.organization_id WHERE e.status='approved' AND e.starts_at>=now() AND e.starts_at<now()+interval '45 days' ORDER BY e.starts_at LIMIT 8`,
 sql`SELECT a.storage_url,a.alt_text,a.caption,a.story_title,a.story_text,a.photo_credit,o.display_name,o.slug FROM organization_assets a JOIN organizations o ON o.id=a.organization_id WHERE a.asset_type='photo' AND a.approved=true AND a.authorization_confirmed=true AND a.newsletter_allowed=true AND (a.minors_present=false OR a.minors_consent_confirmed=true) AND o.active=true AND o.approval_status='approved' ORDER BY a.created_at DESC LIMIT 10`,
 sql`SELECT i.title,i.category,i.quantity_text,b.business_name FROM hub_resource_items i JOIN hub_business_accounts b ON b.id=i.business_id WHERE i.status='available' AND (i.expires_at IS NULL OR i.expires_at>now()) AND b.status='active' ORDER BY i.created_at DESC LIMIT 6`,
 sql`SELECT o.display_name,o.slug,o.mission,o.category,(SELECT a.storage_url FROM organization_assets a WHERE a.organization_id=o.id AND a.asset_type='logo' AND a.approved=true ORDER BY a.created_at DESC LIMIT 1) AS logo_url FROM organizations o WHERE o.active=true AND o.approval_status='approved' AND o.public_status='public' AND o.service_area_verified=true ORDER BY o.last_verified_at DESC NULLS LAST LIMIT 5`,
 sql`SELECT coalesce(sum(resources_posted),0)::int AS resources_posted,coalesce(sum(requests_received),0)::int AS requests_received,coalesce(sum(completed_connections),0)::int AS completed_connections,coalesce(sum(nonprofits_supported),0)::int AS nonprofits_supported FROM hub_business_impact_metrics`
]);const content={needs,events,photos,resources,nonprofits,impact:impact[0]||{}};const monthName=new Date(`${edition}T12:00:00Z`).toLocaleString('en-US',{month:'long',year:'numeric',timeZone:'UTC'}),subject=`LINK Community Brief — ${monthName}`,preview='Local needs, resources, events, people and impact across the Lake Norman community.';const rows=await sql`INSERT INTO hub_community_brief_editions (edition_month,status,subject,preview_text,content_json,generated_at,updated_at) VALUES (${edition},'draft',${subject},${preview},${JSON.stringify(content)}::jsonb,now(),now()) ON CONFLICT (edition_month) DO UPDATE SET status='draft',subject=EXCLUDED.subject,preview_text=EXCLUDED.preview_text,content_json=EXCLUDED.content_json,generated_at=now(),updated_at=now() RETURNING id,edition_month,status,subject,preview_text,content_json`;res.status(200).json({ok:true,edition:rows[0]});}catch(e){console.error('LINK brief generate error:',e);res.status(500).json({ok:false,error:'Community Brief draft could not be generated.'});}}
