import { del,put } from '@vercel/blob';
import { fail,noStore,parse,session } from '../portal/_auth.js';
const types=new Set(['image/jpeg','image/png','image/webp']);
const clean=(v,m=1000)=>String(v??'').trim().slice(0,m);
function decode(v){const m=String(v||'').match(/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/);if(!m||!types.has(m[1]))throw new Error('Use a PNG, JPG or WebP image.');return {type:m[1],buf:Buffer.from(m[2],'base64')};}
function ext(t){return t==='image/png'?'png':t==='image/webp'?'webp':'jpg';}
export default async function handler(req,res){noStore(res);if(req.method!=='POST'){res.setHeader('Allow','POST');fail(res,405,'Method not allowed.');return;}if(!process.env.BLOB_READ_WRITE_TOKEN){fail(res,503,'Photo storage is not configured.');return;}const s=await session(req,res);if(!s)return;try{const body=parse(req),{db,org}=s,action=clean(body.action,40)||'upload';if(action==='delete'){const id=clean(body.assetId,80);const rows=await db`SELECT id,storage_url FROM organization_assets WHERE id=${id} AND organization_id=${org.organization_id} AND asset_type='photo' LIMIT 1`;if(!rows.length){fail(res,404,'Photo not found.');return;}try{await del(rows[0].storage_url);}catch(e){console.warn('LINK nonprofit media blob cleanup:',e?.message||e);}await db`DELETE FROM organization_assets WHERE id=${id} AND organization_id=${org.organization_id}`;res.status(200).json({ok:true});return;}
if(action==='update'){const id=clean(body.assetId,80),minors=body.minorsPresent===true,minorConsent=body.minorsConsentConfirmed===true;if(minors&&!minorConsent){fail(res,400,'Confirm appropriate publication consent for identifiable minors before allowing public or newsletter use.');return;}await db`UPDATE organization_assets SET alt_text=${clean(body.altText,200)||null},caption=${clean(body.caption,500)||null},story_title=${clean(body.storyTitle,180)||null},story_text=${clean(body.storyText,2400)||null},photo_credit=${clean(body.photoCredit,180)||null},public_site_allowed=${body.publicSiteAllowed===true},newsletter_allowed=${body.newsletterAllowed===true},minors_present=${minors},minors_consent_confirmed=${minorConsent},authorization_confirmed=${body.authorizationConfirmed===true},updated_at=now() WHERE id=${id} AND organization_id=${org.organization_id} AND asset_type='photo'`;res.status(200).json({ok:true});return;}
if(body.authorizationConfirmed!==true){fail(res,400,'Confirm your organization has permission to share this photo.');return;}const minors=body.minorsPresent===true,minorConsent=body.minorsConsentConfirmed===true;if(minors&&!minorConsent&&(body.publicSiteAllowed===true||body.newsletterAllowed===true)){fail(res,400,'Confirm appropriate publication consent for identifiable minors.');return;}const {type,buf}=decode(body.dataUrl);if(buf.length>4000000){fail(res,413,'Please use a photo under 4 MB.');return;}const path=`nonprofit-media/${org.organization_id}/${Date.now()}-${Math.random().toString(36).slice(2,9)}.${ext(type)}`;const blob=await put(path,buf,{access:'public',contentType:type});const rows=await db`INSERT INTO organization_assets (organization_id,asset_type,file_name,storage_url,blob_pathname,mime_type,file_size_bytes,authorization_confirmed,approved,alt_text,caption,story_title,story_text,photo_credit,public_site_allowed,newsletter_allowed,minors_present,minors_consent_confirmed,uploaded_by_contact_id,updated_at) VALUES (${org.organization_id},'photo',${clean(body.fileName,240)||'community-photo'},${blob.url},${blob.pathname||path},${type},${buf.length},true,false,${clean(body.altText,200)||null},${clean(body.caption,500)||null},${clean(body.storyTitle,180)||null},${clean(body.storyText,2400)||null},${clean(body.photoCredit,180)||null},${body.publicSiteAllowed===true},${body.newsletterAllowed===true},${minors},${minorConsent},${org.contact_id},now()) RETURNING id,storage_url,approved`;res.status(200).json({ok:true,asset:rows[0],message:'Photo uploaded and submitted for LINK approval.'});}catch(e){console.error('LINK nonprofit media upload error:',e);fail(res,500,e?.message||'Photo could not be uploaded.');}}
